// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-RF1bvIo8Z3FdoP4tOxpEjEG8GnWC3D0',
    appId: '1:362592212474:web:36acebaf538c9ac1adc043',
    messagingSenderId: '362592212474',
    projectId: 'messageboardchat',
    authDomain: 'messageboardchat.firebaseapp.com',
    storageBucket: 'messageboardchat.firebasestorage.app',
    measurementId: 'G-6MD1ZNWBTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlMk8Fwj3Iw3nei_9FH4YQdrZ-sQJHvgY',
    appId: '1:362592212474:android:10d241d0634f4905adc043',
    messagingSenderId: '362592212474',
    projectId: 'messageboardchat',
    storageBucket: 'messageboardchat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEhB-NBSkX1xepQmnOHZxbx9aS_c51fgo',
    appId: '1:362592212474:ios:149d134a3d1987d4adc043',
    messagingSenderId: '362592212474',
    projectId: 'messageboardchat',
    storageBucket: 'messageboardchat.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-RF1bvIo8Z3FdoP4tOxpEjEG8GnWC3D0',
    appId: '1:362592212474:web:e9232e2585e618f8adc043',
    messagingSenderId: '362592212474',
    projectId: 'messageboardchat',
    authDomain: 'messageboardchat.firebaseapp.com',
    storageBucket: 'messageboardchat.firebasestorage.app',
    measurementId: 'G-0D1R1NSN8N',
  );
}
